AWSTemplateFormatVersion: "2010-09-09"

# Setting EC2 parameters
Parameters:
  VpcId:
    Description: "Select specific VPC ID you wish to deploy the EC2 instance to."
    Type: AWS::EC2::VPC::Id
  AmiId:
    Description: "Please type in the AMI ID you wish to use."
    Type: AWS::EC2::Image::Id
    Default: "ami-0ff8a91507f77f867"
    AllowedValues:
      - "ami-0ff8a91507f77f867"
      - "ami-0130c3a072f3832ff"
      - "ami-0023040df18933030"
  InstanceType:
    Description: "Please select the Instance Type."
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
  AZLoc:
    Description: "Please select an a specific AZ to deploy EC2 on."
    Type: String
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c

# Provisioning EC2 instances & settings
Resources:
  # Building the EC2 selections
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AZLoc
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType

  # Creating SecurityGroup for SSH
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
      VpcId: !Ref VpcId
