AWSTemplateFormatVersion: "2010-09-09"

# Setting EC2 parameters
Parameters:
  VpcId:
    Description: "Select specific VPC ID you wish to deploy the EC2 instance to."
    Type: AWS::EC2::VPC::Id
  SourceCidr:
    Description: "Source Cidr range for Source access."
    Type: String
    Default: 72.94.166.0/24
  SubnetId:
    Description: "Defined subnet for EC2 instance."
    Type: AWS::EC2::Subnet::Id
  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Provide the SSM Parameter path to a valid AMI ID
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Description: "Please select the Instance Type."
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium

# Provisioning EC2 instances, IAM Roles & settings
Resources:
  # Create IAM Role
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Grant EC2 access from Systems Manager & CloudWatch."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy"

  # Creating IAM Instance Profile
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref IamRole

  # Building the EC2 selections
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref SubnetId

  # Creating SecurityGroup for SSH
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SourceCidr
      VpcId: !Ref VpcId
